#!/bin/bash
python3 avg_absolute_error_and_thresh.py 0 &
python3 avg_absolute_error_and_thresh.py 1 &
python3 avg_absolute_error_and_thresh.py 2 &
python3 avg_absolute_error_and_thresh.py 3 &
python3 avg_absolute_error_and_thresh.py 4 &
python3 avg_absolute_error_and_thresh.py 5 &
python3 avg_absolute_error_and_thresh.py 6 &
python3 avg_absolute_error_and_thresh.py 7 &
python3 avg_absolute_error_and_thresh.py 8 &
python3 avg_absolute_error_and_thresh.py 9 &
python3 avg_absolute_error_and_thresh.py 10 &
python3 avg_absolute_error_and_thresh.py 11 &
python3 avg_absolute_error_and_thresh.py 12 &
python3 avg_absolute_error_and_thresh.py 13 &
python3 avg_absolute_error_and_thresh.py 14 &
python3 avg_absolute_error_and_thresh.py 15 &
python3 avg_absolute_error_and_thresh.py 16 &
python3 avg_absolute_error_and_thresh.py 17 &
python3 avg_absolute_error_and_thresh.py 18 &
