#!/bin/bash
python3 generate_error_counts.py 0 &
python3 generate_error_counts.py 1 &
python3 generate_error_counts.py 2 &
python3 generate_error_counts.py 4 &
python3 generate_error_counts.py 5 &
python3 generate_error_counts.py 6 &
python3 generate_error_counts.py 7 &
python3 generate_error_counts.py 8 &
python3 generate_error_counts.py 9 &
python3 generate_error_counts.py 10 &
python3 generate_error_counts.py 11 &
python3 generate_error_counts.py 12 &
python3 generate_error_counts.py 13 &
python3 generate_error_counts.py 14 &
python3 generate_error_counts.py 15 &
python3 generate_error_counts.py 16 &
python3 generate_error_counts.py 17 &
python3 generate_error_counts.py 18 &
