#!/bin/bash
python3 make_histogram_per_channel_std_plot.py 0 &
python3 make_histogram_per_channel_std_plot.py 1 &
python3 make_histogram_per_channel_std_plot.py 2 &
python3 make_histogram_per_channel_std_plot.py 3 &
python3 make_histogram_per_channel_std_plot.py 4 &
python3 make_histogram_per_channel_std_plot.py 5 &
python3 make_histogram_per_channel_std_plot.py 6 &
python3 make_histogram_per_channel_std_plot.py 7 &
python3 make_histogram_per_channel_std_plot.py 8 &
python3 make_histogram_per_channel_std_plot.py 9 &
python3 make_histogram_per_channel_std_plot.py 10 &
python3 make_histogram_per_channel_std_plot.py 11 &
python3 make_histogram_per_channel_std_plot.py 12 &
python3 make_histogram_per_channel_std_plot.py 13 &
python3 make_histogram_per_channel_std_plot.py 14 &
python3 make_histogram_per_channel_std_plot.py 15 &
python3 make_histogram_per_channel_std_plot.py 16 &
python3 make_histogram_per_channel_std_plot.py 17 &
python3 make_histogram_per_channel_std_plot.py 18 &
